
# cargo-vet audits file

[[audits.bare-metal]]
who = "Felipe Balbi <felipe.balbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.2.5"

[[audits.bitfield]]
who = "Felipe Balbi <felipe.balbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.13.2"

[[audits.cortex-m]]
who = "Felipe Balbi <felipe.balbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.7.7"

[[audits.cortex-m-rt]]
who = "Felipe Balbi <felipe.balbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.7.5"

[[audits.cortex-m-rt-macros]]
who = "Felipe Balbi <felipe.balbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.7.5"

[[audits.critical-section]]
who = "Felipe Balbi <felipe.balbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "1.2.0"

[[audits.defmt]]
who = "Felipe Balbi <felipe.balbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "1.0.1"

[[audits.defmt-macros]]
who = "Felipe Balbi <felipe.balbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "1.0.1"

[[audits.defmt-parser]]
who = "Felipe Balbi <felipe.balbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "1.0.0"

[[audits.defmt-parser]]
who = "Felipe Balbi <felipe.balbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "1.0.1"

[[audits.embedded-hal]]
who = "Felipe Balbi <felipe.balbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.2.7"

[[audits.proc-macro-error-attr2]]
who = "Felipe Balbi <felipe.balbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "2.0.0"

[[audits.proc-macro-error2]]
who = "Felipe Balbi <felipe.balbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "2.0.1"

[[audits.quote]]
who = "Felipe Balbi <felipe.balbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "1.0.42"

[[audits.rustc_version]]
who = "Felipe Balbi <felipe.balbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.2.3"

[[audits.semver]]
who = "Felipe Balbi <felipe.balbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.9.0"

[[audits.semver-parser]]
who = "Felipe Balbi <felipe.balbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.7.0"

[[audits.syn]]
who = "Felipe Balbi <felipe.balbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "2.0.109"

[[audits.syn]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "2.0.110"

[[audits.syn]]
who = "Felipe Balbi <febalbi@microsoft.com>"
criteria = "safe-to-deploy"
delta = "2.0.110 -> 2.0.109"

[[audits.thiserror]]
who = "Felipe Balbi <felipe.balbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "2.0.17"

[[audits.thiserror-impl]]
who = "Felipe Balbi <felipe.balbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "2.0.17"

[[audits.vcell]]
who = "Felipe Balbi <felipe.balbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.1.3"

[[audits.volatile-register]]
who = "Felipe Balbi <felipe.balbi@microsoft.com>"
criteria = "safe-to-deploy"
version = "0.2.2"

[[trusted.proc-macro2]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2019-04-23"
end = "2026-11-07"

[[trusted.semver]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2021-05-25"
end = "2026-11-07"

[[trusted.unicode-ident]]
criteria = "safe-to-deploy"
user-id = 3618 # David Tolnay (dtolnay)
start = "2021-10-02"
end = "2026-11-07"
